### ISSUE TITLE
Library cannot render a specific IPython notebook

### ISSUE THREAD

**Issue by mrueegg** [jsvine/notebookjs#10]
Hi,

First I want to thank you for your great library!

I experienced a problem with a specific IPython notebook:

https://raw.githubusercontent.com/pybokeh/ipython_notebooks/master/pandas/PandasCheatSheet.ipynb

When I try to render this notebook with your library, I get the following error:

<img width="607" alt="ipython-error" src="https://cloud.githubusercontent.com/assets/206944/23549543/065018a0-000d-11e7-8483-3278079865b8.png">

Note that other IPython notebooks are working fine. Any ideas?

Thanks,
Michael

**Comment by jsvine** [comment]
Thanks, @mrueegg. I'm busy for the next few days, but will take a closer look as soon as I can.

**Comment by mrueegg** [comment]
👍

**Comment by jsvine** [comment]
Thanks again for flagging this, @mrueegg. It was a bug (was using old variable name), which I've now fixed, pushed, and merged.

**Comment by mrueegg** [comment]
👍 Thanks!
