### ISSUE TITLE
State of LaTeX support

### ISSUE THREAD

**Issue by mrueegg** [jsvine/notebookjs#11]
Hi,

I've noticed that you mentioned in the README file that MathJax is currently not supported. I've seen though that in the latest release, there was a fix regarding LaTeX support. I just wanted to ask what this was about and what kind of LaTeX is supported.

Also, if you give me some instructions where to start to support MathJax rendered formulas I would be happy to contribute.

Thanks,
Michael

**Comment by jsvine** [comment]
Thanks, Michael. Does @H-Plus-Time's  proposal here support the features you'd like?: https://github.com/jsvine/notebookjs/pull/8

**Comment by mrueegg** [comment]
@jsvine Yes, that looks great! Are you going to merge this and release a new version?

**Comment by bradhowes** [comment]
FYI, I wrote a separate Katex filter which I use for my static site blog. I run it before doing the notebookjs render. See [notebookjs-katex](https://github.com/bradhowes/notebookjs-katex). Simple, but works great so far.

**Comment by jsvine** [comment]
Neat, and thanks for sharing!

**Comment by bradhowes** [comment]
No problem. Thanks for all the work on notebookjs!

**Comment by jithurjacob** [comment]
Any updates on this?

**Comment by jsvine** [comment]
In-browser KaTeX support is now available in `v0.4.0`, added via https://github.com/jsvine/notebookjs/pull/19.
