### ISSUE TITLE
files size of 1.5 mb take lot of time to load

### ISSUE THREAD

**Issue by vivekangadi1** [jsvine/notebookjs#16]
I basically send the json parsed ipynb data from my frontend angular 6 to backend nodejs which converts and renders me a html code. when the file size is greater than 2mb it gets stuck for ever. i do not get any response. but when the file size is less than 1mb its rendering me the html. i am using notebook.js 0.3.1.. can someone help me in this

**Comment by jsvine** [comment]
Hi @vivekangadi1, is this still causing problems for you? If so, could you provide code/data that reproduces the problem?

Thanks,
Jeremy
