### ISSUE TITLE
Example "Browser usage" may be wrong

### ISSUE THREAD

**Issue by ghost** [jsvine/notebookjs#22]
The example "Browser usage" in README.md does not work for me.
Instead of
```
var notebook = nb.parse(raw_ipynb_json_string);
```
I first needed to parse the raw JSON string into an object:
```
var notebook = nb.parse(JSON.parse(raw_ipynb_json_string));
```

Is this correct or did I overlook something here?

**Comment by jsvine** [comment]
Thank you! You are correct, and this has now been fixed. I appreciate it.
