### ISSUE TITLE
Shrinkwrap file forces repository resolution to public npm registry

### ISSUE THREAD

**Issue by yenoiwesa** [jsvine/notebookjs#32]
Hello there 👋 Thanks for the great library!

Our product is using **notebookjs** to render Jupyter Notebooks in the web browser app, and we currently have a problem with the package registry resolution while executing `npm install`.

Our company uses JFrog's Artifactory as a local proxy and mirror to the public npm registry. We force all packages installed in our project to be resolved from our internal npm mirror via `.npmrc` configuration.

However, this fails for **notebookjs** because the project contains a `shrinkwrap.json` file, that forces the package resolution to the public npm registry (as specified in the shrinkwrap file itself). In addition, it prevents us from fixing transitive vulnerabilities in nested dependencies.

As per the npm documentation on [shrinkwrap.json](https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json):
> The recommended use-case for npm-shrinkwrap.json is applications deployed through the publishing process on the registry: for example, daemons and command-line tools intended as global installs or devDependencies.
It's strongly discouraged for library authors to publish this file, since that would prevent end users from having control over transitive dependency updates.

For libraries, it is advised to use the `package-lock.json` file instead.

Thus, would it be possible to remove the `shrinkwrap.json` file from the repository and replace it with a `package-lock.json` file? Thanks.

**Comment by jsvine** [comment]
Makes sense! Now changed and reflected in v0.6.1 here and on npm.

I'm curious: What's the product?

**Comment by yenoiwesa** [comment]
Thanks for the prompt fix @jsvine ! The product is Bitbucket Server :-)

**Comment by jsvine** [comment]
Neat, and thanks for letting me know!
