### ISSUE TITLE
Bump jsdom dependency from 16.4.0 to 16.6.0 to fix vulnerabilities

### ISSUE THREAD

**Issue by yenoiwesa** [jsvine/notebookjs#35]
Hi there 👋 

Thanks for the great library!

Our security scanning tools have alerted us of two JavaScript vulnerabilities being pulled in our project through `notebookjs`. Both of them are due to the dependency on `"jsdom": "^16.4.0"`: https://github.com/jsvine/notebookjs/blob/master/package.json#L17

Here are the two vulnerabilities:
- `request@2.88.2` high vulnerability on [VeraCode](https://sca.analysiscenter.veracode.com/vulnerability-database/libraries/request/JS/NPM/lid-675/versions/2.88.2)
- `ws@7.4.5` medium vulnerability on [VeraCode](https://sca.analysiscenter.veracode.com/vulnerability-database/libraries/ws/JS/NPM/lid-657/versions/7.4.5)

`ws` version `7.4.6` has fixed the vulnerability, and the dependency that `jsdom` has on it allows us to fix it on our end (compatible versioning).

However that is not the case for `request`, which is deprecated and was entirely removed from `jsdom` [version 16.6.0](https://github.com/jsdom/jsdom/releases/tag/16.6.0).

Would it be possible for `nodebookjs` to change its dependency from`jsdom` `^16.4.0` to `^16.6.0` to fix the vulnerabilities brought through the `request` package? Of course assuming that version `16.6.0` of `jsdom` is compatible with `notebookjs`.

Thank you for your help 😃

**Comment by jsvine** [comment]
Thanks! Dependency now bumped (along with a few others), and available in `v0.6.5` just now pushed to npm.

**Comment by yenoiwesa** [comment]
Thanks @jsvine!
