### ISSUE TITLE
Publishing To Bower

### ISSUE THREAD

**Issue by sbeleidy** [jsvine/notebookjs#4]
Could you please publish notebookjs to bower as well as npm?

**Comment by jsvine** [comment]
Done!

**Comment by sbeleidy** [comment]
Thank you so much! 

I'm working on a web component wrapper for notebookjs so you can embed a Jupyter notebook by simply doing:

``` html
<jupyter-notebook src="path/to/my/notebook.ipynb"></jupyter-notebook>
```

Here's a link to it if you're interested in checking it out https://github.com/sbeleidy/jupyter-notebook. I'd love to get your feedback on it if you get a chance.

Thanks again!

**Comment by jsvine** [comment]
Neat, and thanks for sharing! I don't know much about web component architecture, but your implementation looks pleasantly easy to use.
