### ISSUE TITLE
Could not handle latex

### ISSUE THREAD

**Issue by HavenZhang** [jsvine/notebookjs#5]
May be a typo here:
https://github.com/jsvine/notebookjs/blob/master/notebook.js#L125

```
nb.display.latex = function (latex) {
        var el = makeElement("div", [ "latex-output" ]);
        el.innerHTML = join(latex);
        return el;
    };
```

join -> joinText

**Comment by jsvine** [comment]
Indeed! Many thanks for catching that bug. Fixed and pushed. (Also added you to the "Thanks" section of the README.)
